/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Customer;
import Business.Flight;
import Business.FlightSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZHOU
 */
public class ManageTravelAgencyJPanel extends javax.swing.JPanel {
   
    private TravelAgency travelAgency;
    private JPanel rightJPanel;
    private AirlinerDirectory airlinerDirectory;
    /**
     * Creates new form ManageTravelAgency
     */
    
    public ManageTravelAgencyJPanel(JPanel rightJPanel, TravelAgency travelAgency, AirlinerDirectory airlinerDirectory) {
        initComponents();
        this.travelAgency = travelAgency;
        this.rightJPanel = rightJPanel;
        this.airlinerDirectory = airlinerDirectory;
        populate();
        initialize();
    }
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)tblFlightInfo.getModel();
        dtm.setRowCount(0);
        SimpleDateFormat sdf =  new SimpleDateFormat( " yyyy-MM-dd " );
        for(Airliner a : airlinerDirectory.getAirlinerList()){
            for(Flight f : a.getFlightSchedule().getFlightList()){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = f;
                row[1] = f.getDepartureCity();
                row[2] = f.getArrivingCity();
                row[3] = sdf.format(f.getDepartureTime());
                row[4] = sdf.format(f.getArrivingTime());
                row[5]=  f.getTimeOfDay();
                row[6] = f.getPrice();
                dtm.addRow(row);
            }
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     void initialize(){
        //text should either be "Supplier Login Screen" OR "Customer Login Screen"
        //Based on the selection
        SimpleDateFormat sdf =  new SimpleDateFormat( " yyyy-MM-dd " );
       
        cboDCity.removeAllItems();
        cboACity.removeAllItems();
        cboTime.removeAllItems();
        cboDDate.removeAllItems();
        cboADate.removeAllItems();
        cboCus.removeAllItems();
        cboDCity.addItem("");
        cboACity.addItem("");
        cboTime.addItem("");
        cboDDate.addItem("");
        cboADate.addItem("");
        for(Customer cus:travelAgency.getTravelOffice().getCustomerDirectory().getCustomerList()){
          cboCus.addItem(cus);
        }
        ArrayList<String> listdc = new ArrayList<>();
        for(Airliner a : airlinerDirectory.getAirlinerList()){
            for(Flight f : a.getFlightSchedule().getFlightList()){
                listdc.add(f.getDepartureCity());
            }
        }
        for (int i=0;i<listdc.size()-1;i++){
            for(int j=listdc.size()-1;j>i;j--){
                if(listdc.get(j).equals(listdc.get(i))){
                    listdc.remove(j);
                }
            }
        }
        for(String s:listdc){
            cboDCity.addItem(s);
        }
        
        ArrayList<String> listac = new ArrayList<>();
        for(Airliner a : airlinerDirectory.getAirlinerList()){
            for(Flight f : a.getFlightSchedule().getFlightList()){
                listac.add(f.getArrivingCity());
            }
        }
        for (int i=0;i<listac.size()-1;i++){
            for(int j=listac.size()-1;j>i;j--){
                if(listac.get(j).equals(listac.get(i))){
                    listac.remove(j);
                }
            }
        }
        for(String s:listac){
            cboACity.addItem(s);
        }
        
        cboTime.addItem("Morning");
        cboTime.addItem("Afternoon");
        cboTime.addItem("Evening");
        
        ArrayList<String> listDDate = new ArrayList<>();
        for(Airliner a : airlinerDirectory.getAirlinerList()){
            for(Flight f : a.getFlightSchedule().getFlightList()){
                listDDate.add(sdf.format(f.getDepartureTime()));
            }
        }
        for (int i=0;i<listDDate.size()-1;i++){
            for(int j=listDDate.size()-1;j>i;j--){
                if(listDDate.get(j).equals(listDDate.get(i))){
                    listDDate.remove(j);
                }
            }
        }
        for(String s:listDDate){
            cboDDate.addItem(s);
        } 
        
        ArrayList<String> listADate = new ArrayList<>();
        for(Airliner a : airlinerDirectory.getAirlinerList()){
            for(Flight f : a.getFlightSchedule().getFlightList()){
                listADate.add(sdf.format(f.getArrivingTime()));
            }
        }
        for (int i=0;i<listADate.size()-1;i++){
            for(int j=listADate.size()-1;j>i;j--){
                if(listADate.get(j).equals(listADate.get(i))){
                    listADate.remove(j);
                }
            }
        }
        for(String s:listADate){
            cboADate.addItem(s);
        }

        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightInfo = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboDCity = new javax.swing.JComboBox<>();
        cboTime = new javax.swing.JComboBox<>();
        cboDDate = new javax.swing.JComboBox<>();
        cboACity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboADate = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnCreateCustomer = new javax.swing.JButton();
        cboCus = new javax.swing.JComboBox<>();

        tblFlightInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane", "Departure City", "Arriving City", "Departure time", "Arriving Time", "Time Of Day", "Price($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFlightInfo);
        if (tblFlightInfo.getColumnModel().getColumnCount() > 0) {
            tblFlightInfo.getColumnModel().getColumn(0).setResizable(false);
            tblFlightInfo.getColumnModel().getColumn(1).setResizable(false);
            tblFlightInfo.getColumnModel().getColumn(2).setResizable(false);
            tblFlightInfo.getColumnModel().getColumn(3).setResizable(false);
            tblFlightInfo.getColumnModel().getColumn(4).setResizable(false);
            tblFlightInfo.getColumnModel().getColumn(5).setResizable(false);
            tblFlightInfo.getColumnModel().getColumn(6).setResizable(false);
        }

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnBook.setText("Book A Ticket For Customer");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Travel Agency");

        cboDCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDCityActionPerformed(evt);
            }
        });

        cboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboDDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboACity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Departure City:");

        jLabel3.setText("Arriving City:");

        jLabel4.setText("Time Of Day:");

        jLabel5.setText("Departure Date:");

        cboADate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Arriving Date:");

        btnCreateCustomer.setText("Create Customer");
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });

        cboCus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(cboCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCreateCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboDCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboACity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboDDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboADate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(463, 463, 463))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboDCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboACity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboDDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboADate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
       int selectedRow = tblFlightInfo.getSelectedRow();
        if (selectedRow >= 0) {
            //int selectionButton = JOptionPane.YES_NO_OPTION;
            //int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to update??", "Warning", selectionButton);
            //if (selectionResult == JOptionPane.YES_OPTION) {
                Flight flight = (Flight) tblFlightInfo.getValueAt(selectedRow, 0);
                Customer cus = (Customer)cboCus.getSelectedItem();
                 if(cus.getTicket().getFlight()==null){
                    CustomerBookSeatJPanel customerBookSeatJPanel =new CustomerBookSeatJPanel(rightJPanel,flight, cus);
                    rightJPanel.add("updateCar", customerBookSeatJPanel);
                    CardLayout layout=(CardLayout)rightJPanel.getLayout();
                    layout.next(rightJPanel);
                 }
                 else{
                    JOptionPane.showMessageDialog(null, "A customer can't book second ticket!!");
                    return;
                 }
            }
         else {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        
        
    }//GEN-LAST:event_btnBookActionPerformed

    private void cboDCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDCityActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String DepartureCity =cboDCity.getSelectedItem().toString();
        String ArrivingCity = cboACity.getSelectedItem().toString();
        String Time = cboTime.getSelectedItem().toString();
        String DepartureTime = cboDDate.getSelectedItem().toString();
        String ArrivinigTime = cboADate.getSelectedItem().toString();
        
        FlightSchedule result1 = new FlightSchedule();
        FlightSchedule result = new FlightSchedule();
        for(Airliner a : airlinerDirectory.getAirlinerList()){
            for(Flight f : a.getFlightSchedule().getFlightList()){
                result.getFlightList().add(f);
            }
           
        }
        if(DepartureCity==""){
          result1=result;
        }
        else{
            result1 = result.searchbyDC(DepartureCity);
        }
        
        FlightSchedule result2 = new FlightSchedule();
        if(ArrivingCity==""){
           result2 = result1;
        }
        else{
            result2 = result1.searchbyAC(ArrivingCity);
        }
        
        
        FlightSchedule result3 = new FlightSchedule();
        if(Time==""){
           result3 = result2;
        }
        else{
            result3 = result2.searchbyTime(Time);
        }
        
        
        FlightSchedule result4 = new FlightSchedule();
        if(DepartureTime==""){
           result4 =result3;
        }
        else{
            result4 =result3.searchbyDT(DepartureTime);
        }
        
        FlightSchedule result5 = new FlightSchedule();
        if(DepartureTime==""){
           result5 = result4;
        }
        else{
            result5 = result4.searchAT(ArrivinigTime);
        }
        if(result5.getFlightList().size() == 0){
            JOptionPane.showMessageDialog(null,"There is no matched flight" );
        }
        
        DefaultTableModel dtm = (DefaultTableModel)tblFlightInfo.getModel();
        dtm.setRowCount(0);
        SimpleDateFormat sdf =  new SimpleDateFormat( " yyyy-MM-dd " );
        for(Flight f : result5.getFlightList()){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = f;
                row[1] = f.getDepartureCity();
                row[2] = f.getArrivingCity();
                row[3] = sdf.format(f.getDepartureTime());
                row[4] = sdf.format(f.getArrivingTime());
                row[5]=  f.getTimeOfDay();
                dtm.addRow(row);
                row[6] = f.getPrice();
            }
  
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        // TODO add your handling code here:
        CreateCustomerJPanel jpanel = new CreateCustomerJPanel(this.travelAgency.getTravelOffice(),this.travelAgency.getTravelOffice().getCustomerDirectory(),this.rightJPanel);
        this.rightJPanel.add("CreateCustomerJPanel",jpanel);
        CardLayout layout = (CardLayout) this.rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void cboCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboACity;
    private javax.swing.JComboBox<String> cboADate;
    private javax.swing.JComboBox<Object> cboCus;
    private javax.swing.JComboBox<String> cboDCity;
    private javax.swing.JComboBox<String> cboDDate;
    private javax.swing.JComboBox<String> cboTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlightInfo;
    // End of variables declaration//GEN-END:variables
}
