/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author ZHOU
 */
public class RegisterAirlinerJPanel extends javax.swing.JPanel {

    private TravelAgency travelAgency;
    private JPanel rightJPanel;
    private AirlinerDirectory airlinerDirectory;
    /**
     * Creates new form RegisterAirliners
     */

    public RegisterAirlinerJPanel(JPanel rightJPanel, TravelAgency travelAgency, AirlinerDirectory airlinerDirectory) {
        initComponents();
        
        this.travelAgency = travelAgency;
        this.rightJPanel = rightJPanel;
        this.airlinerDirectory = airlinerDirectory;
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboAirliner = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnViewAirliner = new javax.swing.JButton();
        btnCreateAirliner = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        comboAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAirlinerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabel1.setText("Please select a Airliner:");

        btnViewAirliner.setText("View Airliner Profile");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnCreateAirliner.setText("Create A New Airliner");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Airliners");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnCreateAirliner)
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAirliner)
                            .addComponent(comboAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateAirliner))
                .addGap(18, 18, 18)
                .addComponent(comboAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnViewAirliner)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // TODO add your handling code here:
        CreateAirlinerJPanel jpanel = new CreateAirlinerJPanel(this.rightJPanel,this.travelAgency, this.airlinerDirectory);
        this.rightJPanel.add("CreateAirlinerJPanel",jpanel);
        CardLayout layout = (CardLayout) this.rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here:
        
        Airliner airliner = (Airliner)comboAirliner.getSelectedItem();
        if(airliner == null){
            JOptionPane.showMessageDialog(null, "There is no airliner.");
            return;
        }
        ViewAirlinerJPanel jpanel = new ViewAirlinerJPanel(this.rightJPanel,this.travelAgency,this.airlinerDirectory, airliner);
        this.rightJPanel.add("ViewAirlinerJPanel",jpanel);
        CardLayout layout = (CardLayout) this.rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void comboAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAirlinerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboAirlinerActionPerformed
    public void initialize(){
        comboAirliner.removeAllItems();
        for(Airliner air : this.airlinerDirectory.getAirlinerList()){
            comboAirliner.addItem(air);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JComboBox<Airliner> comboAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
